import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * 开发文档侧边栏配置
 *
 * 使用自动生成模式，Docusaurus会根据development目录的文件结构
 * 自动生成侧边栏导航
 */
const sidebars: SidebarsConfig = {
  developmentSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // 从development目录根开始
    },
  ],

  // 也可以使用手动配置的方式（注释示例）
  // developmentSidebar: [
  //   {
  //     type: 'category',
  //     label: '后端开发',
  //     items: [
  //       'backend/nodejs-guide',
  //       'backend/database',
  //     ],
  //   },
  //   {
  //     type: 'category',
  //     label: '前端开发',
  //     items: [
  //       'frontend/react-guide',
  //       'frontend/styling',
  //     ],
  //   },
  // ],
};

export default sidebars;
